CREATE TABLE DEPARTMENT
(
    ID       INT PRIMARY KEY,
    NAME     VARCHAR(255),
    DESCRIPTION INT,
    STATUS    CHAR
);

CREATE TABLE PRODUCT
(
    ID       INT PRIMARY KEY,
    NAME     VARCHAR(255),
    QUANTITY INT,
    PRICE    decimal
);