version: '3.1'

services:
  mysql:
    container_name: mysql_db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: customer
      MYSQL_USER: mysql
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/app/docker/mysql_data

  postgres:
      container_name: postgres_db
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_DB: creditcard
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root
      ports:
        - "5432:5432"
      volumes:
        - ./postgres_data:/app/docker/postgresql_data